---
title: "A Quick Formatting Overview of RShiny"
author: "Michelle Schmitz"
date: "`r Sys.Date()`"
output: 
  ioslides_presentation:
    widescreen: true
---

<style>
.forceBreak { -webkit-column-break-after: always; break-after: column; }
</style>

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = FALSE)
```

## RShiny: What is it?

Shiny is an R package that makes it easy to build interactive web apps straight from R. 

```
With Shiny, you can:
- host standalone apps on a webpage
- embed them in R Markdown documents
- build (reactive) dashboards
- extend your Shiny apps (with CSS themes, htmlwidgets, and JavaScript actions)
```

<!-- #What are Shiny Apps useful for? -->
<!-- #Interactive data visualisation for presentations and websites -->
<!-- #Sharing results with collaborators -->
<!-- #Communicating science in an accessible way -->
<!-- #Bridging the gap between R users and non-R users -->

## Components of an RShiny App

Within an `app.R` script, there are 2 main components:

- `ui` (user interface script/ _front-end_)
  - controls layout & appearance
  - converts R code to HTML
- `server` (server script/ _back-end_)
  - contains the code needed to build the application

These two scripts are kept in a _single_ R file called **`app.R`**.

_Note: in previous versions of Shiny, the `ui` and `server` sections were set up as two separate scripts, `ui.R` and `server.R`. The application can still work with this format, but it's tidier to keep everything in `app.R`._

## Digging Deeper into the Components (1/3)

**ui**

- Contains information about the layout of the app as it appears in your web browser. 
  - Usually structured using panels that can be laid out in different arrangements, created using nested Shiny functions. 
  - Panels can contain text, widgets, plots, tables, maps, images, etc.

```
## one layout example -- 
# ui.R ----
ui <- fluidPage(
  titlePanel(""),  # Add a title panel
  sidebarLayout(  # Make the layout a sidebarLayout
    sidebarPanel(),  # Inside the sidebarLayout, add a sidebarPanel
    mainPanel()  # Inside the sidebarLayout, add a mainPanel
  )
)

```

## Digging Deeper into the Components (1/3) (cont'd)

- Shiny's user interface is derived based on *functions* (e.g., `fluidPage()`).
- Text can be formatted using approximate equivalents between shiny and HTML5 (e.g., `h2` for `<h2>` for a 2nd-level header)
- Images are set up using an `img(src="FILENAME",height=y,width=x)` argument.
- **Widgets** are interactive web elements that can be interacted with `reactive` elements in the server.
  - Examples include buttons, checkboxes, ranges, radio buttons, help text, sliders, etc.
- Each element/feature is added to the section of the user interface, separated by commas.

## Digging Deeper into the Components (2/3)

**server**

- Part of the script where all code is located for execution of app.
- Contains information about the computation of the app, creating plots, tables, maps etc. using information provided by the user. 
- Usually is basic R code, but can also take in reactive output (*will talk more about this later*)
- Can define how often a code is run based on placement in the script
  - Can put sourcing code before the `shinyServer()` call
  - Placing code within the `shinyServer()` function, *but not in an output*, will run once when a user visits an app.
  - Placing code within an output and a render function (*more later*) will change *every time someone modifies a widget*.

## Digging Deeper into the Components (2/3) (cont'd)

```
# server.R ----
server <- function(input, output) {
  output$plot <- renderPlot(ggplot(Barley, aes(x = yield)) +  # Create object called `output$plot` with a ggplot inside it
  geom_histogram(bins = 7,  # Add a histogram to the plot
    fill = "grey",  # Make the fill colour grey
    data = Barley,  # Use data from `Barley`
    colour = "black")  # Outline the bins in black
  )                                                       
}
```

## Digging Deeper into the Components (3/3)

**app.R** (combines the server + ui blocks)

- A command to run the app. _This should be included at the very end of app.R._
- Tells Shiny that the user interface comes from the object called ui and that the server information (data, plots, tables, etc.) comes from the object called server.

```
# Run the app ----
shinyApp(ui = ui, server = server)
```

Note: if you were using the separate `ui.R` and `server.R` formats, you would use the below syntax instead:

```
# Run the app (old version)----
shinyServer(function(input,output){
[text here]
})
```

<!-- ## All Together - A Basic R Script -->

<!-- ``` -->
<!--  library(shiny)  # Required to run any Shiny app -->
<!--  library(ggplot2)  # For creating pretty plots -->
<!--  library(dplyr)  # For filtering and manipulating data -->

<!--  # Loading data ---- -->
<!--  Barley <- as.data.frame(beaven.barley) ## or read in data source -->

<!--  # ui.R ---- -->
<!--  ui <- fluidPage() -->

<!--  # server.R ---- -->
<!--  server <- function(input, output) {} -->

<!--  # Run the app ---- -->
<!--  shinyApp(ui = ui, server = server) -->
<!--  ``` -->


## More on Reactive Outputs

- Using widgets allows users to interact with the application - *reactive output* is the response to the interaction.
- Adding widgets/reactive outputs into an app has 2 steps:
  1. Add an R object/widget to the UI to indicate where it goes on the page)
    - Has 1 argument (a name)  - an `Output function` (Appendix 1)
  2. Add instructions on how to build object in the server
    - Within the server, all objects in the UI need to be defined using the prefix `output$`, followed by the name of the object.
    - Object name has a `render function` associated with it to do a certain action (see Appendix 2)  

## Fun Additions

- **Reactive expressions** are similar to reactive outputs, but allow one to interactive decide when certain parts of the app update (e.g., reactive data frames)
- **Interactive Visualizations** can let you make interactive maps/charts - such as plotly, d3, Google Charts, etc.
- **Progress Bars** can help users to gauge the progress of a calculation.
- There's a *lot* of stuff available if you know where to look - make sure to look around.

## Sharing Shiny Applications

You can either:

- Share files with an R user who know how to use it, such as:
  - Zip file
  - GitHub
- Share as a webpage, either on:
  - Server-side hosting an app
  - Free-standing online website (at [shinyapps.io](shinyapps.io))
  - Free-standing application on the Linux-based Shiny Server

## Tutorial Links to Follow

- [RShiny Landing Page](https://shiny.rstudio.com)
- [RShiny Tutorial from RStudio](https://shiny.rstudio.com/tutorial/)
- [RMarkdown Cheatsheet](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf)
- [Basic RShiny Tutorial](https://ourcodingclub.github.io/tutorials/shiny/)
- [Introduction to Shiny for R](https://www.slideshare.net/Sheffield_R_/introduction-to-shiny-for-r)

## Appendix 1: Output Functions

<!-- why on earth are you not rendering correctly, table?! -->

This is what you put into a UI to tell it where to output the desired object.

    | Output Function   | creates...        |
    |-------------------|-------------------|
    | `htmlOutput`      | raw HTML          |
    | `imageOutput`     | image             |
    | `plotOutput`      | plot              |
    | `tableOutput`     | table             |
    | `textOutput`      | text              | 

## Appendix 2: Render Functions

<!-- why on earth are you not rendering correctly, table?! -->

This is what you put into the server-side (back-end) to create the object.

    | render Function       | creates...                                    |
    |-----------------------|-----------------------------------------------|
    | `renderImage`         | images                                        |
    | `renderPlot`          | plot                                          |
    | `renderPrint`         | any printed output                            |
    | `renderTable`         | data frame, matrix, other table structures    |
    | `renderText`          | character strings                             |
    | `renderUI`            | a Shiny tag object/HTML                       |
